[package]
name = "olvweb"
version = "0.1.0"
authors = ["Ian Rehwinkel <ian.rehwinkel@tutanota.com>"]
edition = "2018"

[dependencies]
olive_script = { path = "../.." }
httparse = "1.3.4"

[lib]
name = "web"
crate-type = ["cdylib"]
path = "src/lib.rs"