[package]
name = "olvmath"
version = "0.1.0"
authors = ["Ian Rehwinkel <ian.rehwinkel@tutanota.com>"]
edition = "2018"

[dependencies]
olive_script = { path = "../.." }

[lib]
name = "math"
crate-type = ["cdylib"]
path = "src/lib.rs"