[package]
name = "oliveparser"
version = "0.1.0"
authors = ["Ian Rehwinkel <ian.rehwinkel@tutanota.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "^0.19"

[build-dependencies]
lalrpop = { version = "^0.19", features = ["lexer"] }